### ISSUE TITLE
Test not working

### ISSUE THREAD

**Issue by ajd394** [MVLSLAW/WaterBillScraper#1]
@MatthewExpungement It seems that this tool is not working currently. i ran `php test.php` . Any thoughts as to why? I am willing to help fix it :)

**Comment by MatthewExpungement** [comment]
Hey good catch. There error were two old post values that I thought never or rarely changed so they were hard coded in. I added a new method which grabs new versions of these each time, hopefully eliminating the need for this in the future. Let me know if you get the test.php working.

**Comment by ajd394** [comment]
Ok thanks! i will test it out soon!
